console – fBlog
console Subroutine
Source File
public subroutine console()
Uses:
iso_fortran_env
Arguments
None
Description
Head routine for console mode.
Calls
Source Code
  subroutine console()
    !! Head routine for console mode.
    !
    use, intrinsic :: iso_fortran_env, only: compiler_version, compiler_options
    !
    print '(a,2/,a,2/)', show_version, compiler_version() // ' (' // compiler_options() // ')'
    inquire(file = path // fblog_dir // '.', exist = file_exist)
    if (.not. file_exist) then
       inquire(file = path // FBLOG_DIR // '.', exist = directory_exist)
       if (.not. directory_exist) then
          call execute_command_line(command = 'stty -g > ' // path // 'stty_g', exitstat = exit_status, cmdstat = command_status,&
               & cmdmsg = command_msg)
          if (exit_status /= 0 .or. command_status /= 0) call terminate(error_code = 1131, cmd_msg = command_msg)
          open(newunit = lu_stty_g, file = path // 'stty_g', status = 'old', action = 'read', iostat = ios, iomsg = system_msg)
          if (ios /= 0) call terminate(error_code = 1132, sys_msg = system_msg)
          read(unit = lu_stty_g, fmt = '(a)') terminal_settings
          close(unit = lu_stty_g, status = 'delete')
       else if (directory_exist) then
          call execute_command_line(command = 'stty -g > ' // path // fblog_dir //'stty_g', exitstat = exit_status, cmdstat =&
               & command_status, cmdmsg = command_msg)
          if (exit_status /= 0 .or. command_status /= 0) call terminate(error_code = 1133, cmd_msg = command_msg)
          open(newunit = lu_stty_g, file = path // fblog_dir // 'stty_g', status = 'old', action = 'read', iostat = ios, iomsg =&
               & system_msg)
          if (ios /= 0) call terminate(error_code = 1134, sys_msg = system_msg)
          read(unit = lu_stty_g, fmt = '(a)') terminal_settings
          close(unit = lu_stty_g, status = 'delete')
       end if
       choice = console_menu(i18n(quit) // ',' // i18n(create_new_blog))
       select case (choice)
       case ('q', 'Q', '0')
          print '(a)', bye
          call terminate(error_code = 0)
       case ('1')
          call create_blog()
          print '(a)', ok
       case default
          call terminate(error_code = 1135, inf_msg = i18n(wrong_entry))
       end select
    end if
    call execute_command_line(command = 'stty -g > ' // trim(path) // fblog_dir //'stty_g', exitstat = exit_status, cmdstat =&
         & command_status, cmdmsg = command_msg)
    if (exit_status /= 0 .or. command_status /= 0) call terminate(error_code = 1136, cmd_msg = command_msg)
    open(newunit = lu_stty_g, file = path // fblog_dir // 'stty_g', status = 'old', action = 'read', iostat = ios, iomsg =&
         & system_msg)
    if (ios /= 0) call terminate(error_code = 1137, sys_msg = system_msg)
    read(unit = lu_stty_g, fmt = '(a)') terminal_settings
    close(unit = lu_stty_g, status = 'delete')
    call init_conf()
    call menu_main()
    error stop 'Internal error in subroutine console()'
  end subroutine console
Call graph
console calls i18n, init_conf, create_blog, menu_main, terminate, console_menu
menu_main calls i18n, menu_main, terminate, console_menu, init_data, config, update, menu_page, menu_css, menu_post
console_menu calls terminate
menu_page calls i18n, menu_main, terminate, console_menu, menu_page, list_pages, delete_page, edit_page
menu_css calls i18n, menu_main, terminate, console_menu, menu_css, delete_css, list_css, edit_css
menu_post calls i18n, menu_main, terminate, console_menu, menu_post, edit_post, list_posts, add_post, delete_post