console_menu – fBlog
console_menu Function
Source File
private function console_menu(items)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: items
Return Value character(len=1)
Description
Auxilary routine for displaying the menus in console mode.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
character(len=1), public :: keystroke
character(len=80), public, dimension(10) :: item
character(len=len(items)), public :: read_items
integer, public :: command_status = 0
integer, public :: exit_status = 0
integer, public :: i
integer, public :: ios
integer, public :: j
integer, public :: k
integer, public :: pos
Source Code
  function console_menu(items)
    !! Auxilary routine for displaying the menus in console mode.
    character(len=*), intent(in) :: items
    character(len=1) console_menu
    integer :: command_status = 0, exit_status = 0, i, ios, j, k, pos
    character(len=len(items)) :: read_items
    character(len=80), dimension(10) :: item
    character(len=1)   :: keystroke
    !
    read_items = items
    j = 1
    do i = 1, 10
       pos = index(string = read_items(:), substring = ",")
       if ((pos == 0) .and. (len_trim(read_items) == 0)) exit
       if ((pos == 0) .and. (len(read_items) > 0)) then
          item(i) = read_items
          exit
       end if
       item(i) = read_items(:pos-1)
       read_items = read_items(pos+1:)
       j =  j + 1
    end do
    write(unit = *, fmt = '(a)', advance = 'no') set_bold
    do k = 1, j
       print '(2x,i1,a)', k-1, "  " // trim(item(k))
    end do
    print '(a)', ga
    call execute_command_line(command = 'stty raw', exitstat = exit_status, cmdstat = command_status, cmdmsg = command_msg)
    if (exit_status /= 0 .or. command_status /= 0) call terminate(error_code = 1231, cmd_msg = command_msg)
    write(unit = *, fmt = '(a)', advance = 'no') set_blue
    read(unit = *, fmt = '(a)', advance = 'no', iostat  = ios) keystroke
    write(unit = *, fmt = '(a)', advance = 'no') reset
    call execute_command_line(command = 'stty ' // trim(terminal_settings), exitstat = exit_status, cmdstat = command_status,&
         & cmdmsg = command_msg)
    if (exit_status /= 0 .or. command_status /= 0) call terminate(error_code = 1232, cmd_msg = command_msg)
    print *
    console_menu = keystroke
  end function console_menu
Call graph
console_menu calls terminate
console calls console_menu, menu_main
menu_page calls console_menu, menu_page, menu_main
menu_css calls console_menu, menu_css, menu_main
menu_post calls console_menu, menu_post, menu_main
menu_main calls console_menu, menu_page, menu_css, menu_post, menu_main