create_blog – fBlog
create_blog Subroutine
Source File
public subroutine create_blog()
Arguments
None
Description
Create directories, files and install a new blog.
Calls
Variables
Type Visibility Attributes Name Initial
character(len=1), public :: char_i
character(len=10), public :: t
character(len=19), public :: file_name_entry = ""
character(len=256), public :: command_msg = ""
character(len=256), public :: system_msg = ""
character(len=8), public :: d
integer, public :: command_status = 0
integer, public :: exit_status = 0
integer, public :: i
integer, public :: ios
integer, public :: lu_config
integer, public :: lu_page
integer, public :: lu_post
integer, public :: lu_style
integer, public :: lu_style_print
logical, public :: file_exist
Source Code
  subroutine create_blog()
    !! Create directories, files and install a new blog.
    !
    logical :: file_exist
    integer :: command_status = 0, exit_status = 0, i, ios, lu_config, lu_page, lu_post, lu_style, lu_style_print
    character(len=1)   :: char_i
    character(len=8)   :: d
    character(len=10)  :: t
    character(len=19)  :: file_name_entry = ""
    character(len=256) :: command_msg = "", system_msg  = ""
    !
    config_txt = config_txt_1 // "CSS=fBlog-" // version // ".css" // new_line('a') // "" // new_line('a') // "CSS_PRINT&
         &=fBlog_print-" // version // ".css" // new_line('a') // "" // new_line('a') // config_txt_2
    inquire(file = path // fblog_dir // '.', exist = file_exist)
    if (file_exist) call terminate(error_code = 1021, inf_msg = i18n(there_is_already_a_blog))
    print '(a)', i18n(the_folowing_files_and_directories_will_be_created), path // fblog_dir, path // config_file, path //&
         & data_dir, path // export_html_dir, path // styles_dir, path // styles_dir // "fBlog-" // version // ".css", path //&
         & styles_dir // "fBlog_print-" // version // ".css", path // pages_dir, path // pages_dir // "page1 to page3.html"
    ! Create main directory.
    call execute_command_line(command = "mkdir " // path // fblog_dir, exitstat = exit_status, cmdstat = command_status, cmdmsg =&
         & command_msg)
    if (exit_status /= 0 .or. command_status /= 0) call terminate(error_code = 1022, cmd_msg = command_msg)
    ! Create subdirectory for data.
    call execute_command_line(command = "mkdir " // path // data_dir, exitstat = exit_status, cmdstat = command_status, cmdmsg =&
         & command_msg)
    if (exit_status /= 0 .or. command_status /= 0) call terminate(error_code = 1023, cmd_msg = command_msg)
    ! Create subdirectory for output.
    call execute_command_line(command = "mkdir "// path // export_html_dir, exitstat = exit_status, cmdstat = command_status,&
         & cmdmsg = command_msg)
    if (exit_status /= 0 .or. command_status /= 0) call terminate(error_code = 1024, cmd_msg = command_msg)
    ! Create subdirectory for CSSs.
    call execute_command_line(command = "mkdir " // path // styles_dir, exitstat = exit_status, cmdstat = command_status, cmdmsg =&
         & command_msg)
    if (exit_status /= 0 .or. command_status /= 0) call terminate(error_code = 1025, cmd_msg = command_msg)
    ! Create subdirectory for static pages.
    call execute_command_line(command = "mkdir "// path // pages_dir, exitstat = exit_status, cmdstat = command_status, cmdmsg =&
         & command_msg)
    if (exit_status /= 0 .or. command_status /= 0) call terminate(error_code = 1026, cmd_msg = command_msg)
    ! Begin config file generation.
    open(newunit = lu_config, file = path // config_file, status = 'new', action = 'write', iostat = ios, iomsg = system_msg)
    if (ios /= 0) call terminate(error_code = 1027, sys_msg = system_msg)
    if (ios == 0) write(unit = lu_config, fmt = '(a)') config_txt
    ! End of config file generation.
    close(unit = lu_config)
    ! Begin style sheets generation.
    open(newunit = lu_style, file  = path // styles_dir // "fBlog-" // version // ".css", status = 'new', action = 'write', iostat&
         & = ios, iomsg = system_msg)
    if (ios /= 0) call terminate(error_code = 1028, sys_msg = system_msg)
    if (ios == 0) write(unit = lu_style, fmt = '(a)')  css_standard
    ! End style sheet generation.
    close(unit = lu_style)
    ! Begin style sheets generation.
    open(newunit = lu_style_print, file = path // styles_dir // "fBlog_print-" // version // ".css", status = 'new', action =&
         & 'write', iostat = ios, iomsg = system_msg)
    if (ios /= 0) call terminate(error_code = 1029, sys_msg = system_msg)
    if (ios == 0) write(unit = lu_style_print, fmt = '(a)') css_standard_print
    ! End style sheet generation.
    close(unit = lu_style_print)
    create_3_pages: do i = 1, 3
       ! Create demo static pages.
       write(unit = char_i, fmt = '(i1)') i
       open(newunit = lu_page, file = path // pages_dir // "page" // char_i // ".html", status = 'new', action = 'write', iostat =&
            & ios)
       if (ios /= 0) cycle
       write(unit = lu_page, fmt = '(a)') "<h2>Page #" // char_i // "</h2>" // new_line('a') // "<h3>" // empty_page // "</h3>"
       close(unit = lu_page)
    end do create_3_pages
    ! Create 1 entry.
    call date_and_time(date = d, time = t)
    file_name_entry = d // t(1:6) // '.blog'
    open(newunit = lu_post, file = path // data_dir // file_name_entry, action = 'write', iostat = ios, iomsg = system_msg)
    if (ios /= 0) call terminate(error_code = 1030, sys_msg = system_msg)
    write(unit = lu_post, fmt = '(a)') lorem_ipsum
    close(unit = lu_post)
    if(allocated(config_txt)) deallocate(config_txt)
    call update()
  end subroutine create_blog
Call graph
create_blog calls update, terminate, i18n