edit_post – fBlog
edit_post Subroutine
Source File
public subroutine edit_post(rank, recorded)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: rank
logical, intent(out) :: recorded
Description
Display the editor to edit a post entry that already exist.
Calls
Variables
Type Visibility Attributes Name Initial
character(len=19), public :: edit_file
character(len=256), public :: command_msg = ""
integer, public :: command_status = 0
integer, public :: exit_status = 0
integer, public :: file_size_after
integer, public :: file_size_before
Source Code
  subroutine edit_post(rank, recorded)
    !! Display the editor to edit a post entry that already exist.
    integer, intent(in)  :: rank
    logical, intent(out) :: recorded
    integer :: command_status = 0, exit_status = 0, file_size_after, file_size_before
    character(len=19)  :: edit_file
    character(len=256) :: command_msg = ""
    !
    recorded = .true. ! Initialisation required.
    call init_conf()
    call init_data()
    if (rank > total_entries .or. rank <= 0 ) call terminate(error_code = 1081, inf_msg = i18n(this_number_is_wrong ))
    edit_file = data_post(rank,6)%date // '.blog'
    inquire(file = path // data_dir // trim(edit_file(1:19)), size = file_size_before)
    call execute_command_line(command = editor//' '// path // data_dir // trim((edit_file(1:19))), exitstat = exit_status, cmdstat&
         & = command_status, cmdmsg = command_msg)
    if (exit_status /= 0 .or. command_status /= 0) call terminate(error_code = 1082, cmd_msg = command_msg)
    ! Check if size of the file has changed. If not, it is supposed that file wasn't modified. (Not always true!)
    inquire(file = path // data_dir // trim(edit_file(1:19)), size = file_size_after)
    if (file_size_before == file_size_after) recorded = .false.
  end subroutine edit_post
Call graph
edit_post calls init_conf, data_post, init_data, i18n, terminate