html_month_archive – fBlog
html_month_archive Subroutine
Source File
private subroutine html_month_archive(n_pages)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: n_pages
Description
Make HTML code for monthly index pages.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
character(len=12), public :: m_archive2
character(len=256), public :: system_msg
character(len=6), public :: m_archive
character(len=6), public :: m_archive1 = ""
integer, public :: current_entry
integer, public :: i
integer, public :: ios
integer, public :: j
integer, public :: k
integer, public :: lu_m_archive
logical, public :: file_exist
Source Code
  subroutine html_month_archive(n_pages)
    !! Make HTML code for monthly index pages.
    !  This routine is a shame. But it works... Maybe I'll rewrite it in the future.
    integer, intent(out) :: n_pages
    logical :: file_exist
    integer :: current_entry, i, ios, j, k, lu_m_archive
    character(len=6)   :: m_archive
    character(len=6)   :: m_archive1 = ""
    character(len=12)  :: m_archive2
    character(len=256) :: system_msg
    !
    n_pages = 0
    do current_entry = 1, total_entries
       m_archive = data_post(current_entry,6)%date(1:6)
       do i = 1, total_entries
          if (m_archive == m_archive1) cycle
          if (data_post(i,6)%date(1:6) /= m_archive) cycle
          if (i > 1) then
             if (data_post(i-1,6)%date(1:6) == m_archive) cycle
          end if
          inquire(file = path // export_html_dir // data_post(current_entry,6)%date(1:6) // ".html", exist = file_exist)
          if (file_exist) cycle
          m_archive1 = m_archive
          open(newunit = lu_m_archive, file = path // export_html_dir // data_post(current_entry,6)%date(1:6) // ".html", action&
               & = 'write', iostat = ios, iomsg = system_msg)
          if (ios /= 0) call terminate(error_code = 1181, sys_msg = system_msg)
          write(unit = lu_m_archive, fmt = '(a)') header_1, '<title>' // blog_title // ' | ' // trim(archive) // ' ' //&
               & data_post(current_entry,6)%date(1:4) // '-' // data_post(current_entry,6)%date(5:6) // '</title>' // header_2
          if (len(menu_html) > 0) write(unit = lu_m_archive, fmt  = '(a)') '<nav>', '<hr />', menu_html // '<hr />', '</nav>'
          write(unit = lu_m_archive, fmt = '(a)') '<article>','<header>','<h3>' // trim(archive) // '<span dir="ltr"><code> [' &
               &// data_post(current_entry,6)%date(1:4) // '-' // data_post(current_entry,6)%date(5:6) // ']</code></span></h3>'&
               &,'</header>', '<ol>'
          k=1
          do j = 1, total_entries
             m_archive2 = data_post(j,6)%date(1:12)
             if (m_archive2(1:6) /= m_archive1) cycle
             write(unit = lu_m_archive, fmt = '(a)') '<li><span dir="ltr"><code>[' // data_post(j,6)%date(1:4) // '-' //&
                  & data_post(j,6)%date(5:6) // '-' // data_post(j,6)%date(7:8) // ' (' // data_post(j,6)%date(9:10) // ':' //&
                  & data_post(j,6)%date(11:12) // ')] </code></span>&nbsp;<a href="' // data_post(j,6)%date(1:14) // '.html' //&
                  & '">' // trim(adjustl(data_post(j,7)%post_title)) // '</a></li>'
             K = k + 1
          end do
          write(unit = lu_m_archive, fmt = '(a)') '</ol>', '</article>', footer_1
          close(unit = lu_m_archive)
          n_pages = n_pages + 1
       end do
    end do
  end subroutine html_month_archive
Call graph
html_month_archive calls terminate
terminate calls i18n
update calls html_month_archive