i18n – fBlog
i18n Function
Source File
public function i18n(msg)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: msg
Return Value character(len=:), allocatable
Description
Provide sentences in the language according the LANG environment variable.
Called By
Variables
Type Visibility Attributes Name Initial
character(len=2), public :: lang
character(len=256), public, dimension(en:fr, 0:wrong_entry) :: msgstr = ""
Internationalization of messages according setting of LANG (English, French...)
integer, public :: l = 0
integer, public :: stat
Source Code
  function i18n(msg)
    !! Provide sentences in the language according the LANG environment variable.
    integer, intent(in) :: msg
    character(:), allocatable :: i18n
    integer :: l = 0, stat
    character(len=2) lang
    character(len=256), dimension(en:fr, 0:wrong_entry) :: msgstr = ""
    !
    include 'i18n.inc'
    !
    call get_environment_variable(name = "LANG", value = lang, status = stat)
    if (lang == "en") l = en
    if (lang == "fr") l = fr
    str_i18n = trim(msgstr(l,msg))
    if (len(str_i18n) == 0) str_i18n = trim(msgstr(en,msg))
    i18n = str_i18n
    deallocate(str_i18n)
  end function i18n
Call graph
terminate calls i18n
update calls i18n, terminate, init_data, html_home, html_year_archive, html_page, init_conf, html_permalink, html_month_archive
init_data calls i18n, terminate
html_home calls terminate
html_year_archive calls terminate
html_page calls terminate
init_conf calls terminate
html_permalink calls terminate
html_month_archive calls terminate