init_data – fBlog
init_data Subroutine
Source File
public subroutine init_data()
Uses:
iso_fortran_env
Arguments
None
Description
Collect titles and dates of entries. (This is the second step of two.)
Calls
Called By
Variables
Type Visibility Attributes Name Initial
character(len=256), public :: command_msg = ""
character(len=256), public :: system_msg
character(len=512), public :: readline
character(len=512), public :: readline1
integer, public :: command_status = 0
integer, public :: exit_status = 0
integer, public :: file_length
integer, public :: intreadline
integer, public :: intreadline1
integer, public :: i
integer, public :: ios
integer, public :: j
integer, public :: lu_lstmp
integer, public :: lu_post
integer, public :: lu_wrong
Source Code
  subroutine init_data()
    !! Collect titles and dates of entries. (This is the second step of two.)
    use, intrinsic :: iso_fortran_env, only: &
         iostat_end
    integer :: command_status = 0, exit_status = 0, file_length, intreadline, intreadline1, i, ios, j, lu_lstmp, lu_post,&
         & lu_wrong
    character(len=256) :: command_msg = "", system_msg
    character(len=512) :: readline, readline1
    !
    if (allocated(data_post)) deallocate(data_post)
    if (allocated(stats)) deallocate(stats)
    call execute_command_line(command = 'ls -r ' // path // data_dir // ' > ' // path // fblog_dir // 'data_list.txt', exitstat =&
         & exit_status, cmdstat = command_status, cmdmsg = command_msg)
    if (exit_status /= 0 .or. command_status /= 0) call terminate(error_code = 1121, cmd_msg = command_msg)
    open(newunit = lu_lstmp, file = path // fblog_dir // "data_list.txt", action = 'read', status = 'old', iostat = ios, iomsg =&
         & system_msg)
    if (ios /= 0) call terminate(error_code = 1122, sys_msg    = system_msg)
    do
       read(unit = lu_lstmp, fmt = '(a)', iostat = ios) readline
       if (ios == iostat_end) exit
       if (len(trim(readline)) /= 19) then
          open(newunit = lu_wrong, file = path // data_dir // trim(readline), status = 'old', iostat = ios, iomsg = system_msg)
          if (ios /= 0) call terminate(error_code = 1123, sys_msg = system_msg)
          print *, i18n(is_deleted) // path // data_dir // trim(readline)
          close(unit = lu_wrong, status = 'delete')
          read(unit = lu_lstmp, fmt = '(a)', iostat = ios) readline
          if (ios == iostat_end) exit
       end if
       inquire(file = path // data_dir // trim(readline), size = file_length)
       if (file_length < 2) then
          open(newunit = lu_wrong, file = path // data_dir // trim(readline), status = 'old', iostat = ios, iomsg = system_msg)
          if (ios /= 0) call terminate(error_code = 1124, sys_msg = system_msg)
          print *, i18n(is_deleted) // path // data_dir // trim(readline)
          close(unit = lu_wrong, status = 'delete')
       end if
    end do
    close(unit = lu_lstmp)
    call execute_command_line(command = 'ls -r ' // path // data_dir // ' > ' // path // FBLOG_DIR // 'data_list.txt', exitstat =&
         & exit_status, cmdstat = command_status, cmdmsg = command_msg)
    if (exit_status /= 0 .or. command_status /= 0) call terminate(error_code = 1125, cmd_msg = command_msg)
    open(newunit = lu_lstmp, file = path // fblog_dir // "data_list.txt", action = 'read', status = 'old', iostat = ios, iomsg =&
         & system_msg)
    if (ios /= 0) call terminate(error_code = 1126, sys_msg = system_msg)
    total_entries = 0
    do
       read(unit = lu_lstmp, fmt = '(a)', iostat = ios) readline
       if (ios == iostat_end) exit
       total_entries = total_entries + 1
    end do
    if (total_entries == 0) then
       close(unit = lu_lstmp, status = 'delete')
       return
    end if
    rewind(unit = lu_lstmp)
    allocate(data_post(1:total_entries, 1:7))
    readline = ""
    do i = 1, total_entries
       read(unit = lu_lstmp, fmt = '(a)') readline
       data_post(i,6)%date = trim(readline(1:14))
       open(newunit = lu_post, file = path // data_dir // trim(readline), action = 'read', iostat = ios, iomsg = system_msg)
       if (ios /= 0) call terminate(error_code = 1127, sys_msg = system_msg)
       read(unit = lu_post, fmt = '(a)') readline1
       data_post(i,7)%post_title = trim(readline1)
       read(unit = readline(1:4), fmt = *) intreadline
       data_post(i,1)%year = intreadline
       read(unit = readline(5:6), fmt = *) intreadline
       data_post(i,2)%month = intreadline
       read(unit = readline(7:8), fmt = *) intreadline
       data_post(i,3)%day = intreadline
       read(unit = readline(9:10), fmt = *) intreadline
       data_post(i,4)%hour = intreadline
       read(unit = readline(11:12), fmt = *) intreadline
       data_post(i,5)%minute = intreadline
       read(unit = readline(13:14), fmt = *) intreadline
       data_post(i,6)%seconde = intreadline
       data_post(i,7)%post_title = trim(readline1)
       close(unit = lu_post)
    end do
    year1 = data_post(1,1)%year
    year2 = data_post(total_entries,1)%year
    allocate(stats(year2:year1,0:14))
    stats(year2:year1,0:14) = 0
    do j = year2, year1
       stats(j,0) = j
    end do
    rewind(unit = lu_lstmp)
    do
       read(unit = lu_lstmp, fmt = '(a)', iostat = ios) readline
       if (ios == iostat_end) exit
       read(unit = readline(1:4), fmt = *) intreadline
       read(unit = readline(5:6), fmt = *) intreadline1
       stats(intreadline, intreadline1) = stats(intreadline,intreadline1) + 1
    end do
    close(unit = lu_lstmp, status = 'delete')
  end subroutine init_data
Call graph
init_data calls terminate, i18n
terminate calls i18n
update calls init_data