list_posts – fBlog
list_posts Subroutine
Source File
public subroutine list_posts(limit)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: limit
Description
Display a list of post entries (last ones or all of them).
Calls
Variables
Type Visibility Attributes Name Initial
integer, public :: i
logical, public :: ok_limit
Source Code
  subroutine list_posts(limit)
    !! Display a list of post entries (last ones or all of them).
    integer,intent(in), optional :: limit
    logical :: ok_limit
    integer :: i
    !
    ok_limit = present(limit)
    call init_data()
    if (ok_limit) then
       if (limit < total_entries) total_entries = limit
    end if
    if (total_entries == 0) print'(a)', i18n(no_post)
    do i = total_entries, 1, -1
       print '(a,g0,a)', '#', i, ' [' // data_post(i,6)%date(1:4) // '-' // data_post(i,6)%date(5:6) // '-' // data_post(i,6)&
            &%date(7:8) // ' (' // data_post(i,6)%date(9:10) // ':' // data_post(i,6)%date(11:12) // ')] ' // trim(data_post(i,7)&
            &%post_title)
    end do
  end subroutine list_posts
Call graph
list_posts calls data_post, init_data, i18n