menu_page – fBlog
menu_page Subroutine
Source File
private recursive subroutine menu_page()
Arguments
None
Description
Provide sub menu for static pages in console mode.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
character(len=1), public :: choice
character(len=512), public :: page_2_delete
character(len=512), public :: page_2_edit
logical, public :: page_has_been_recorded
Source Code
  recursive subroutine menu_page()
    !! Provide sub menu for static pages in console mode.
    character(len=1)   :: choice
    character(len=512) :: page_2_delete, &
         page_2_edit
    logical :: page_has_been_recorded
    !
    choice = console_menu(                    &
         i18n(up) // ',' //                   &
         i18n(show_full_list_pages) // ',' // &
         i18n(edit_a_page) // ',' //          &
         i18n(delete_a_page)                  &
         )
    select case (choice)
    case ('q', 'Q')
       print '(a)', bye
       call terminate(error_code = 0)
    case ('0')
       call menu_main()
    case ('1')
       call list_pages
       print '(a)', ok
       call menu_page()
    case ('2')
       write(unit = *, fmt = '(a)', advance = 'no') i18n(enter_the_filename_of_the_page_created) // " "
       read(unit = *, fmt  = *) page_2_edit
       print '(a,g0,a)', set_blue, trim(page_2_edit), reset
       call edit_page(page2edit = page_2_edit, recorded = page_has_been_recorded)
       if (page_has_been_recorded) then
          print '(a)',  i18n(edited_page) // " " // trim(page_2_edit) // new_line('a') // i18n(now_you_could_edit_settings), ok
       else
          print '(a)', i18n(not_modified), ok
       end if
       call menu_page()
    case ('3')
       write(unit = *, fmt = '(a)', advance = 'no') i18n(enter_the_filename_of_the_page_deleted) // " "
       read(unit = *, fmt = *) page_2_delete
       print '(a,g0,a)', set_blue, trim(page_2_delete), reset
       call delete_page(page2delete = page_2_delete)
       print '(a)', i18n(deleted_page) // " " // trim(page_2_delete) // new_line('a') // i18n(now_you_could_edit_settings), ok
       call menu_page()
    case default
       print '(a)', false_entry // i18n(wrong_entry) // reset
       call menu_page()
    end select
  end subroutine menu_page
Call graph
menu_page calls menu_page, list_pages, delete_page, edit_page, menu_main, terminate, console_menu, i18n
menu_main calls menu_page, menu_main, terminate, console_menu, i18n, init_data, config, update, menu_css, menu_post
console_menu calls terminate
menu_css calls menu_main, terminate, console_menu, i18n, menu_css, delete_css, list_css, edit_css
menu_post calls menu_main, terminate, console_menu, i18n, menu_post, edit_post, list_posts, add_post, delete_post
console calls menu_main