menu_main – fBlog
menu_main Subroutine
Source File
private recursive subroutine menu_main()
Uses:
iso_fortran_env
Arguments
None
Description
Provide top menu in console mode.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
character(len=1), public :: choice
logical, public :: config_has_been_recorded
Source Code
  recursive subroutine menu_main()
    !! Provide top menu in console mode.
    use, intrinsic :: iso_fortran_env, only: compiler_version, compiler_options
    logical :: config_has_been_recorded
    character(len=1) :: choice
    !
    choice = console_menu(          &
         i18n(quit) // ',' //       &
         i18n(update_all) // ',' // &
         i18n(posts) // ',' //      &
         i18n(pages) // ',' //      &
         i18n(styles) // ',' //     &
         i18n(edit_settings)        &
         )
    select case (choice)
    case ('q', 'Q', '0')
       print '(a)', bye
       call terminate(error_code = 0)
    case ('1')
       call update()
       print '(a)', ok
       call menu_main()
    case ('2')
       call init_data()
       call menu_post()
    case ('3')
       call menu_page()
    case ('4')
       call menu_css()
    case ('5')
       call config(recorded = config_has_been_recorded)
       if (config_has_been_recorded) then
          print '(a)', i18n(now_you_should_update), ok
       else
          print '(a)', i18n(not_modified), ok
       end if
       call menu_main()
    case default
       print '(a)', false_entry // i18n(wrong_entry) // reset
       call menu_main()
    end select
  end subroutine menu_main
Call graph
menu_main calls menu_main, init_data, config, update, menu_page, menu_css, terminate, console_menu, menu_post, i18n
menu_page calls menu_main, menu_page, terminate, console_menu, i18n, list_pages, delete_page, edit_page
menu_css calls menu_main, menu_css, terminate, console_menu, i18n, delete_css, list_css, edit_css
console_menu calls terminate
menu_post calls menu_main, terminate, console_menu, menu_post, i18n, edit_post, list_posts, add_post, delete_post
console calls menu_main