menu_post – fBlog
menu_post Subroutine
Source File
private recursive subroutine menu_post()
Arguments
None
Description
Provide sub menu for post entries in console mode.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
character(len=1), public :: choice
integer, public :: int_keystroke
integer, public :: ios
integer, public :: rank_val
logical, public :: post_has_been_recorded
Source Code
  recursive subroutine menu_post()
    !! Provide sub menu for post entries in console mode.
    character(len=1) :: choice
    integer :: int_keystroke, ios, rank_val
    logical :: post_has_been_recorded
    !
    if (total_entries > 0) then
       choice = console_menu(               &
            i18n(up) // ',' //              &
            i18n(show_last_posts) // ',' // &
            i18n(new_post) // ',' //        &
            i18n(modify_a_post) // ',' //   &
            i18n(delete_a_post) // ',' //   &
            i18n(show_full_list_posts)      &
            )
       select case (choice)
       case ('q', 'Q')
          print '(a)', bye
          call terminate(error_code = 0)
       case ('0')
          call menu_main()
       case ('1')
          call list_posts(limit = post_amount)
          print '(a)', ok
          call menu_post()
       case ('2')
          print '(a)', ok
          call add_post(recorded = post_has_been_recorded)
          if (post_has_been_recorded) then
             print '(a)', i18n(now_you_should_update), ok
          else
             print '(a)', i18n(not_modified), ok
          end if
          call menu_main()
       case ('3')
          write(unit = *, fmt = '(a)', advance = 'no') i18n(enter_the_rank_of_the_post_to_modify) // " "
          read(unit = *, fmt = *, iostat = ios) int_keystroke
          if (ios /= 0) call terminate(error_code = 1141, inf_msg = i18n(wrong_entry))
          rank_val = int_keystroke
          print '(a,g0,a)', set_blue, rank_val, reset
          call edit_post(rank = rank_val, recorded = post_has_been_recorded)
          if (post_has_been_recorded) then
             print '(a)', i18n(now_you_should_update), ok
          else
             print '(a)', i18n(not_modified), ok
          end if
          call menu_main()
       case ('4')
          write(unit = *, fmt = '(a)', advance = 'no') i18n(enter_the_rank_of_the_post_to_delete) // " "
          read(unit = *, fmt = *, iostat = ios) int_keystroke
          if (ios /= 0) call terminate(error_code = 1142, inf_msg = i18n(wrong_entry))
          rank_val = int_keystroke
          print '(a,g0,a)', set_blue, rank_val, reset
          call delete_post(rank = rank_val)
          print '(a, g0, 2a)', i18n(deleted_file) // " ", rank_val, new_line('a'), i18n(now_you_should_update)
          print '(a)', ok
          call menu_main()
       case ('5')
          call list_posts()
          print '(a)', ok
          call menu_post()
       case default
          print '(a)', false_entry // i18n(wrong_entry) // reset
          call menu_post()
       end select
    else
       choice = console_menu(  &
            i18n(up) // ',' // &
            i18n(new_post)     &
            )
       select case (choice)
       case ('q', 'Q')
          print '(a)', bye
          call terminate(error_code = 0)
       case ('0')
          call menu_main()
       case ('1')
          call add_post(recorded = post_has_been_recorded)
          print '(a)', ok
          if (post_has_been_recorded) then
             print '(a)', i18n(now_you_should_update), ok
          else
             print '(a)', i18n(not_modified), ok
          end if
          call menu_main()
       case default
          print '(a)', false_entry
          call menu_post()
       end select
    end if
  end subroutine menu_post
Call graph
menu_post calls menu_post, i18n, edit_post, list_posts, add_post, menu_main, terminate, console_menu, delete_post
menu_main calls menu_post, i18n, menu_main, terminate, console_menu, init_data, config, update, menu_page, menu_css
console_menu calls terminate
menu_page calls i18n, menu_main, terminate, console_menu, menu_page, list_pages, delete_page, edit_page
menu_css calls i18n, menu_main, terminate, console_menu, menu_css, delete_css, list_css, edit_css
console calls menu_main