menu_css – fBlog
menu_css Subroutine
Source File
private recursive subroutine menu_css()
Arguments
None
Description
Provide a sub menu for CSS in console mode.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
character(len=1), public :: choice
character(len=512), public :: css_2_delete
character(len=512), public :: css_2_edit
logical, public :: css_has_been_recorded
Source Code
  recursive subroutine menu_css()
    !! Provide a sub menu for CSS in console mode.
    logical :: css_has_been_recorded
    character(len=1)   :: choice
    character(len=512) :: css_2_delete, css_2_edit
    !
    choice = console_menu(                  &
         i18n(up) // ',' //                 &
         i18n(show_full_list_css) // ',' // &
         i18n(edit_a_css) // ',' //         &
         i18n(delete_a_css)                 &
         )
    select case (choice)
    case ('q', 'Q')
       print '(a)', bye
       call terminate(error_code = 0)
    case ('0')
       call menu_main()
    case ('1')
       call list_css()
       print '(a)', ok
       call menu_css()
    case ('2')
       write(unit = *, fmt = '(a)', advance = 'no') i18n(enter_the_filename_of_the_page_created) // " "
       read(unit = *, fmt = '(a)') css_2_edit
       print '(a,g0,a)', set_blue, trim(css_2_edit), reset
       call edit_css(css2edit = css_2_edit, recorded = css_has_been_recorded)
       if (css_has_been_recorded) then
          print '(a)', i18n(now_you_should_update), ok
       else
          print '(a)', i18n(not_modified), ok
       end if
       call menu_css()
    case ('3')
       write(unit = *, fmt = '(a)', advance = 'no') i18n(enter_the_filename_of_the_css_deleted) // " "
       read(unit = *, fmt = *) css_2_delete
       print '(a,g0,a)', set_blue, trim(css_2_delete), reset
       call delete_css(css2delete = css_2_delete)
       print '(a)', i18n(is_deleted) // " " // trim(css_2_delete), ok
       call menu_css()
    case default
       print '(a)', false_entry // i18n(wrong_entry) // reset
       call menu_css()
    end select
  end subroutine menu_css
Call graph
menu_css calls menu_css, i18n, delete_css, menu_main, list_css, edit_css, console_menu, terminate
menu_main calls menu_css, i18n, menu_main, console_menu, terminate, init_data, config, update, menu_page, menu_post
console_menu calls terminate
menu_page calls i18n, menu_main, console_menu, terminate, menu_page, list_pages, delete_page, edit_page
menu_post calls i18n, menu_main, console_menu, terminate, menu_post, edit_post, list_posts, add_post, delete_post
console calls menu_main