terminate – fBlog
terminate Subroutine
Source File
public subroutine terminate(error_code, cmd_msg, inf_msg, sys_msg)
Uses:
iso_fortran_env
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: error_code
character(len=*), intent(in), optional :: cmd_msg
character(len=*), intent(in), optional :: inf_msg
character(len=*), intent(in), optional :: sys_msg
Description
Double role: error function and normal terminaison of job. In case of malfunction, an error code is provided. This error code gives location of the failure in source code.
1000 -> 1010 subroutine add_post 1011 -> 1020 subroutine config 1021 -> 1030 subroutine create_blog 1031 -> 1040 subroutine delete_css 1041 -> 1050 subroutine delete_page 1051 -> 1060 subroutine delete_post 1061 -> 1070 subroutine edit_css 1071 -> 1080 subroutine edit_page 1081 -> 1090 subroutine edit_post 1091 -> 1100 program main 1111 -> 1120 subroutine init_conf 1121 -> 1130 subroutine init_data 1131 -> 1140 subroutine console 1141 -> 1150 subroutine menu_post 1151 -> 1160 subroutine list_css 1161 -> 1170 subroutine list_pages 1171 -> 1180 subroutine html_home 1181 -> 1190 subroutine html_month_archive 1191 -> 1200 subroutine html_permalink 1201 -> 1210 subroutine html_year_archive 1211 -> 1220 subroutine update 1221 -> 1230 subroutine html_page 1231 -> 1240 function console_menu 1241 -> 1250 subroutine html_permalink
Calls
Called By
Variables
Type Visibility Attributes Name Initial
character(len=*), public, parameter :: move_cursor_left = '[20D'
Source Code
  subroutine terminate(error_code, cmd_msg, inf_msg, sys_msg)
    !! Double role: error function and normal terminaison of job. In case of malfunction,
    !! an error code is provided. This error code gives location of the failure in source
    !! code.
    !
    use, intrinsic :: iso_fortran_env, only: error_unit
    !
    integer, intent(in) :: error_code
    character(len=*), intent(in), optional :: cmd_msg
    character(len=*), intent(in), optional :: inf_msg
    character(len=*), intent(in), optional :: sys_msg
    character(len=*), parameter :: move_cursor_left = '[20D'
    !
    if (allocated(archive))          deallocate(archive)
    if (allocated(blog_title))       deallocate(blog_title)
    if (allocated(charset))          deallocate(charset)
    if (allocated(css_file))         deallocate(css_file)
    if (allocated(css_print_file))   deallocate(css_print_file)
    if (allocated(data_post))        deallocate(data_post)
    if (allocated(description))      deallocate(description)
    if (allocated(editor))           deallocate(editor)
    if (allocated(footer))           deallocate(footer)
    if (allocated(footer_1))         deallocate(footer_1)
    if (allocated(header_1))         deallocate(header_1)
    if (allocated(header_2))         deallocate(header_2)
    if (allocated(home))             deallocate(home)
    if (allocated(language))         deallocate(language)
    if (allocated(menu_html))        deallocate(menu_html)
    if (allocated(path))             deallocate(path)
    if (allocated(permalink))        deallocate(permalink)
    if (allocated(printer_friendly)) deallocate(printer_friendly)
    if (allocated(stats))            deallocate(stats)
    !
    !! 1000 -> 1010  subroutine add_post
    !! 1011 -> 1020  subroutine config
    !! 1021 -> 1030  subroutine create_blog
    !! 1031 -> 1040  subroutine delete_css
    !! 1041 -> 1050  subroutine delete_page
    !! 1051 -> 1060  subroutine delete_post
    !! 1061 -> 1070  subroutine edit_css
    !! 1071 -> 1080  subroutine edit_page
    !! 1081 -> 1090  subroutine edit_post
    !! 1091 -> 1100  program main
    !! 1111 -> 1120  subroutine init_conf
    !! 1121 -> 1130  subroutine init_data
    !! 1131 -> 1140  subroutine console
    !! 1141 -> 1150  subroutine menu_post
    !! 1151 -> 1160  subroutine list_css
    !! 1161 -> 1170  subroutine list_pages
    !! 1171 -> 1180  subroutine html_home
    !! 1181 -> 1190  subroutine html_month_archive
    !! 1191 -> 1200  subroutine html_permalink
    !! 1201 -> 1210  subroutine html_year_archive
    !! 1211 -> 1220  subroutine update
    !! 1221 -> 1230  subroutine html_page
    !! 1231 -> 1240  function console_menu
    !! 1241 -> 1250  subroutine html_permalink
    !
    if (error_code /= 0) then
       if (len(trim(sys_msg)) > 0) write(unit = error_unit, fmt = '(3a)') i18n(system_said), " ", trim(sys_msg)
       if (len(trim(cmd_msg)) > 0) write(unit = error_unit, fmt = '(3a)') i18n(shell_said), " ", trim(cmd_msg)
       if (present(inf_msg)) write(unit = error_unit, fmt = '(a)') trim(inf_msg)
       write(unit = error_unit, fmt = '(t12,g0,a)', advance = 'no') error_code, char(27) // move_cursor_left
       error stop
    else
       if (present(inf_msg)) print'(a)', trim(inf_msg)
       stop
    end if
    error stop 'Internal error in subroutine Terminate'
  end subroutine terminate
Call graph
terminate calls i18n
update calls terminate, html_home, html_year_archive, html_page, init_conf, init_data, html_permalink, html_month_archive
html_home calls terminate
html_year_archive calls terminate
html_page calls terminate
init_conf calls terminate
init_data calls terminate
html_permalink calls terminate
html_month_archive calls terminate