update – fBlog
update Subroutine
Source File
public subroutine update()
Arguments
None
Description
Build all pages of the blog. The most important procedure of the project! This procedure could be called from an other program by including in it module fblog_m.
Calls
Variables
Type Visibility Attributes Name Initial
character(len=256), public :: command_msg = ""
integer, public :: command_status = 0
integer, public :: count_archive_pages
integer, public :: count_css = 0
integer, public :: count_pages = 0
integer, public :: exit_status = 0
logical, public :: file_exist
Source Code
  subroutine update()
    !! Build all pages of the blog. The most important procedure of the project!
    !! This procedure could be called from an other program by including in it module fblog_m.
    logical :: file_exist
    integer :: command_status = 0, count_archive_pages, count_css = 0, count_pages = 0, exit_status = 0
    character(len=256) :: command_msg = ""
    !
    call init_data()
    call init_conf()
    header_1 = '<!DOCTYPE html>'
    if ((len(language) == 0) .and. (direction == "ltr")) header_1 = header_1 // nl // '<html>'
    if ((len(language) == 0) .and. (direction == "rtl")) header_1 = header_1 // nl // '<html dir="rtl">'
    if ((len(language) > 1) .and. (direction == "ltr")) header_1 = header_1 // nl // '<html lang="' // language // '">'
    if ((len(language) > 1) .and. (direction == "rtl")) header_1 = header_1 // nl // '<html lang="' // language // '" dir="rtl">'
    header_1 = header_1 // nl // '<head>' // nl // '<meta charset=' // '"' // charset // '" />' // nl // '<meta name="generator"&
         & content="fBlog ' // VERSION // '" />'
    if (css) header_2 = nl // '<link rel="stylesheet" href="' // css_file // '" type="text/css" media="all" />' // nl // '</head>'&
         & // nl // '<body>' // nl // '<header>' // nl // '<h1><a href="index.html">' // blog_title // '</a></h1>' // nl // '<&
         &/header>'
    if (len(description) > 0) header_2 = header_2 // nl // '<aside>' // nl // description // '</aside>'
    if (len(footer) > 0) footer_1 = '<footer>' // nl // '<hr />' // nl // footer // '</footer>' // nl // '</body>'// nl // '</html&
         &>'
    print '(a)', clock() // i18n(begin_update)
    print '(a)', clock() // i18n(initialisation_reading_data)
    print '(a)', clock() // i18n(initialisation_reading_conf)
    inquire(file = path // export_html_dir // 'index.html', exist = file_exist)
    if (file_exist) then
       print '(6a)', clock(), i18n(make_clear_subdirectory), "./", path, export_html_dir, "'"
       call execute_command_line(command = "rm "// path // export_html_dir // "*", wait=.true., exitstat = exit_status, cmdstat =&
            & command_status, cmdmsg = command_msg)
       if (exit_status /= 0 .or. command_status /= 0) call terminate(error_code = 1211, cmd_msg = command_msg)
       print '(6a)', clock(), i18n(end_clearing_subdirectory), "./", path, export_html_dir, "'"
    end if
    if (total_entries > 1) then
       print '(6a)', clock(), i18n(make_permalink_pages), "./", path, export_html_dir, "ccyymmddhhmmss.htm(l)'"
       call html_permalink()
       print '(a,g0,a)', clock(), 2 * total_entries, " " // i18n(permalink_pages_built)
       call html_month_archive(n_pages = count_archive_pages)
       print '(a,g0,2a)', clock(), count_archive_pages, " ", i18n(monthly_archive_pages_built)
       print '(7a)', clock(), i18n(make_archive_pages), "./", path, export_html_dir, archive, ".html'"
       call html_year_archive()
    end if
    print '(6a)', clock(), i18n(make_home_page), "./", path, export_html_dir, "index.html'"
    call html_home(user_home = home)
    print '(6a)', clock(), i18n(make_pages), "./", path, export_html_dir, "*.html'"
    call html_page(n_pages = count_pages)
    print '(a,g0,2a)', clock(), count_pages, " ", i18n(pages_built)
    if (css) then
       print '(7a)', clock(), i18n(copy_css), "./", path, export_html_dir, css_file, "'"
       call execute_command_line(command = "cp " // path // styles_dir // css_file // " " // path // export_html_dir, exitstat =&
            & exit_status, cmdstat = command_status, cmdmsg = command_msg)
       if (exit_status /= 0 .or. command_status /= 0) call terminate(error_code = 1212, inf_msg = i18n(error_css))
    else
       print'(a)', i18n(warn_about_no_css)
    end if
    if (css_print .and. (total_entries > 1)) then
       print '(7a)', clock(), i18n(copy_css_print), "./", path, export_html_dir, css_print_file, "'"
       call execute_command_line(command = "cp " // path // styles_dir // css_print_file // " " // path // export_html_dir,&
            & exitstat = exit_status, cmdstat = command_status, cmdmsg = command_msg)
       if (exit_status /= 0 .or. command_status /= 0) call terminate(error_code = 1213, inf_msg = i18n(error_css_print))
    else
       if (css_print .and. (total_entries > 1)) print'(a)', i18n(warn_about_no_css_print)
    end if
    print '(2a)', clock(), i18n(update_done)
    if (css) count_css = 1
    if (css_print .and. (total_entries > 1)) count_css = count_css + 1
    if (total_entries < 2) print '(g0,6a)', count_pages + 1 + count_css, " ", i18n(files_generated_inside_the_subdirectory), &
         & "./", path, export_html_dir, "'"
    if (total_entries > 1)print '(g0,6a)', count_archive_pages + (2 * total_entries) + count_pages + 2 + count_css, " ",&
         & i18n(files_generated_inside_the_subdirectory), "./" // path, export_html_dir, "'"
  end subroutine update
Call graph
update calls terminate, html_home, html_year_archive, clock, html_page, init_conf, i18n, html_permalink, init_data, html_month_archive
terminate calls i18n
html_home calls terminate
html_year_archive calls terminate
html_page calls terminate
init_conf calls terminate
html_permalink calls terminate
init_data calls terminate, i18n
html_month_archive calls terminate